import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import User from '../models/User.js';
import { generateToken, JWT_SECRET } from '../middleware/authMiddleware.js';

const publicUser = (user) => ({ id: user.id, name: user.name, email: user.email, role: user.role, status: user.status });
export async function register(req, res, next) { try { const { name, email, password, role = 'Receptionist' } = req.body; if (!name || !email || !password) return res.status(400).json({ success: false, message: 'Name, email, and password are required' }); if (password.length < 6) return res.status(400).json({ success: false, message: 'Password must be at least 6 characters' }); if (await User.exists({ email: email.toLowerCase() })) return res.status(409).json({ success: false, message: 'Email already registered' }); const user = await User.create({ name, email, password: await bcrypt.hash(password, 10), role }); return res.status(201).json({ success: true, message: 'User registered successfully', token: generateToken(user), user: publicUser(user) }); } catch (error) { return next(error); } }
export async function login(req, res, next) { try { const { email, password } = req.body; if (!email || !password) return res.status(400).json({ success: false, message: 'Email and password are required' }); const user = await User.findOne({ email: email.toLowerCase() }).select('+password'); if (!user || !user.isActive || !(await bcrypt.compare(password, user.password))) return res.status(401).json({ success: false, message: 'Invalid email or password' }); return res.json({ success: true, message: 'Login successful', token: generateToken(user), user: publicUser(user) }); } catch (error) { return next(error); } }
export async function getCurrentUser(req, res, next) { try { const user = await User.findById(req.user.id); if (!user) return res.status(404).json({ success: false, message: 'User not found' }); return res.json({ success: true, user: publicUser(user) }); } catch (error) { return next(error); } }
export function verifyToken(req, res) { const token = req.headers.authorization?.startsWith('Bearer ') ? req.headers.authorization.slice(7) : null; if (!token) return res.status(401).json({ success: false, valid: false, message: 'No token provided' }); try { return res.json({ success: true, valid: true, user: jwt.verify(token, JWT_SECRET()) }); } catch { return res.status(401).json({ success: false, valid: false, message: 'Token is invalid or expired' }); } }