import FoodItem from '../models/FoodItem.js';
import FoodOrder from '../models/FoodOrder.js';
import Invoice from '../models/Invoice.js';
import Payment from '../models/Payment.js';

export async function getFoodItems(req, res, next) { try { return res.json({ success: true, data: await FoodItem.find().sort({ category: 1, name: 1 }) }); } catch (error) { return next(error); } }
export async function createFoodItem(req, res, next) { try { return res.status(201).json({ success: true, data: await FoodItem.create(req.body) }); } catch (error) { return next(error); } }
export async function updateFoodItem(req, res, next) { try { const data = await FoodItem.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true }); if (!data) return res.status(404).json({ success: false, message: 'Food item not found' }); return res.json({ success: true, data }); } catch (error) { return next(error); } }
export async function deleteFoodItem(req, res, next) { try { const data = await FoodItem.findByIdAndDelete(req.params.id); if (!data) return res.status(404).json({ success: false, message: 'Food item not found' }); return res.json({ success: true, data }); } catch (error) { return next(error); } }
export async function getFoodOrders(req, res, next) { try { return res.json({ success: true, data: await FoodOrder.find().populate('guest').populate('items.foodItem').sort({ createdAt: -1 }) }); } catch (error) { return next(error); } }
export async function createFoodOrder(req, res, next) { try { const items = (req.body.items || []).map((item) => ({ ...item, subtotal: Number(item.price || 0) * Number(item.quantity || 1) })); const totalAmount = items.reduce((sum, item) => sum + item.subtotal, 0); const data = await FoodOrder.create({ ...req.body, items, totalAmount, orderNumber: `ORD-${Date.now()}`, createdBy: req.user?.id }); return res.status(201).json({ success: true, message: 'Order placed successfully', data }); } catch (error) { return next(error); } }
export async function updateFoodOrder(req, res, next) { try { const data = await FoodOrder.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true }); if (!data) return res.status(404).json({ success: false, message: 'Order not found' }); return res.json({ success: true, data }); } catch (error) { return next(error); } }
export async function getInvoices(req, res, next) { try { const data = await Invoice.find().populate('guest').populate('reservation').sort({ createdAt: -1 }); return res.json({ success: true, data }); } catch (error) { return next(error); } }
export async function getInvoice(req, res, next) { try { const data = await Invoice.findById(req.params.id).populate('guest').populate('reservation'); if (!data) return res.status(404).json({ success: false, message: 'Invoice not found' }); return res.json({ success: true, data }); } catch (error) { return next(error); } }
export async function createInvoice(req, res, next) { try { const totalAmount = Number(req.body.roomCharges || 0) + Number(req.body.foodCharges || 0) + Number(req.body.additionalCharges || 0) - Number(req.body.discount || 0); return res.status(201).json({ success: true, data: await Invoice.create({ ...req.body, totalAmount, invoiceNumber: `INV-${Date.now()}` }) }); } catch (error) { return next(error); } }
export async function getPayments(req, res, next) { try { return res.json({ success: true, data: await Payment.find().populate('invoice').populate('guest').sort({ paymentDate: -1 }) }); } catch (error) { return next(error); } }
export async function getPayment(req, res, next) { try { const data = await Payment.findById(req.params.id); if (!data) return res.status(404).json({ success: false, message: 'Payment not found' }); return res.json({ success: true, data }); } catch (error) { return next(error); } }
export async function createPayment(req, res, next) { try { const data = await Payment.create({ ...req.body, paymentNumber: `PAY-${Date.now()}`, processedBy: req.user?.id }); if (data.invoice) await Invoice.findByIdAndUpdate(data.invoice, { $inc: { amountPaid: data.amount } }); return res.status(201).json({ success: true, data }); } catch (error) { return next(error); } }
export async function updatePayment(req, res, next) { try { const selector = /^[0-9a-fA-F]{24}$/.test(req.params.id) ? { _id: req.params.id } : { paymentNumber: req.params.id }; const status = req.body.status === 'Paid' ? 'Completed' : req.body.status; const data = await Payment.findOneAndUpdate(selector, { status }, { new: true, runValidators: true }); if (!data) return res.status(404).json({ success: false, message: 'Payment not found' }); return res.json({ success: true, data }); } catch (error) { return next(error); } }