import mongoose from 'mongoose';
import Reservation from '../models/Reservation.js';
import Guest from '../models/Guest.js';
import Room from '../models/Room.js';

const activeStatuses = { $nin: ['Cancelled', 'Checked Out'] };
const populate = (query) => query.populate('guest').populate('room').populate('createdBy', 'name email role');
const byId = (id) => mongoose.isValidObjectId(id) ? { _id: id } : { reservationNumber: id };
const dateOnly = (value) => new Date(`${value}T00:00:00.000Z`);
const conflictQuery = (room, checkInDate, checkOutDate, exclude) => ({ room, status: activeStatuses, checkInDate: { $lt: dateOnly(checkOutDate) }, checkOutDate: { $gt: dateOnly(checkInDate) }, ...(exclude ? { _id: { $ne: exclude } } : {}) });

export async function getAllReservations(req, res, next) { try { const data = await populate(Reservation.find().sort({ createdAt: -1 })); return res.json({ success: true, count: data.length, data }); } catch (error) { return next(error); } }
export async function getReservationById(req, res, next) { try { const data = await populate(Reservation.findOne(byId(req.params.id))); if (!data) return res.status(404).json({ success: false, message: 'Reservation not found' }); return res.json({ success: true, data }); } catch (error) { return next(error); } }
export async function createReservation(req, res, next) { try { const { guestId, roomId, checkInDate, checkOutDate, adults, children, status = 'Pending', specialRequests } = req.body; if (!guestId || !roomId || !checkInDate || !checkOutDate) return res.status(400).json({ success: false, message: 'Guest ID, room ID, check-in date, and check-out date are required' }); const inDate = dateOnly(checkInDate); const outDate = dateOnly(checkOutDate); if (Number.isNaN(inDate.getTime()) || Number.isNaN(outDate.getTime()) || outDate <= inDate) return res.status(400).json({ success: false, message: 'Check-out date must be after check-in date' }); const [guest, room, conflict] = await Promise.all([Guest.findById(guestId), Room.findById(roomId), Reservation.exists(conflictQuery(roomId, checkInDate, checkOutDate))]); if (!guest) return res.status(404).json({ success: false, message: 'Guest not found' }); if (!room) return res.status(404).json({ success: false, message: 'Room not found' }); if (conflict) return res.status(409).json({ success: false, message: 'Room is not available for the selected dates.' }); const nights = Math.ceil((outDate - inDate) / 86400000); const data = await Reservation.create({ reservationNumber: `RES-${Date.now()}`, guest: guestId, room: roomId, checkInDate: inDate, checkOutDate: outDate, adults: Number(adults) || 1, children: Number(children) || 0, status, totalAmount: room.price * nights, specialRequests, createdBy: req.user?.id }); if (status === 'Confirmed') await Room.findByIdAndUpdate(roomId, { status: 'Reserved' }); return res.status(201).json({ success: true, message: 'Reservation created successfully', data: await populate(Reservation.findById(data._id)) }); } catch (error) { return next(error); } }
export async function updateReservationData(req, res, next) { try { const current = await Reservation.findOne(byId(req.params.id)); if (!current) return res.status(404).json({ success: false, message: 'Reservation not found' }); const { checkInDate, checkOutDate, adults, children, status, specialRequests } = req.body; const nextIn = checkInDate || current.checkInDate.toISOString().slice(0, 10); const nextOut = checkOutDate || current.checkOutDate.toISOString().slice(0, 10); if (dateOnly(nextOut) <= dateOnly(nextIn)) return res.status(400).json({ success: false, message: 'Check-out date must be after check-in date' }); if (checkInDate || checkOutDate) { const conflict = await Reservation.exists(conflictQuery(current.room, nextIn, nextOut, current._id)); if (conflict) return res.status(409).json({ success: false, message: 'Room is not available for the selected dates.' }); } const room = await Room.findById(current.room); const updates = { ...(checkInDate && { checkInDate: dateOnly(nextIn) }), ...(checkOutDate && { checkOutDate: dateOnly(nextOut) }), ...(adults !== undefined && { adults: Number(adults) }), ...(children !== undefined && { children: Number(children) }), ...(status !== undefined && { status }), ...(specialRequests !== undefined && { specialRequests }) }; if (checkInDate || checkOutDate) updates.totalAmount = room.price * Math.ceil((dateOnly(nextOut) - dateOnly(nextIn)) / 86400000); const data = await populate(Reservation.findOneAndUpdate(byId(req.params.id), updates, { new: true, runValidators: true })); return res.json({ success: true, message: 'Reservation updated successfully', data }); } catch (error) { return next(error); } }
export async function deleteReservationData(req, res, next) { try { const data = await populate(Reservation.findOneAndUpdate(byId(req.params.id), { status: 'Cancelled' }, { new: true })); if (!data) return res.status(404).json({ success: false, message: 'Reservation not found' }); return res.json({ success: true, message: 'Reservation cancelled successfully', data }); } catch (error) { return next(error); } }
export async function getReservationsByGuest(req, res, next) { try { const data = await populate(Reservation.find({ guest: req.params.guestId }).sort({ createdAt: -1 })); return res.json({ success: true, data }); } catch (error) { return next(error); } }
export async function getReservationStats(req, res, next) { try { const [totalReservations, confirmedReservations, pendingReservations, completedReservations, cancelledReservations, revenue] = await Promise.all([Reservation.countDocuments(), Reservation.countDocuments({ status: 'Confirmed' }), Reservation.countDocuments({ status: 'Pending' }), Reservation.countDocuments({ status: 'Checked Out' }), Reservation.countDocuments({ status: 'Cancelled' }), Reservation.aggregate([{ $match: { status: { $ne: 'Cancelled' } } }, { $group: { _id: null, total: { $sum: '$totalAmount' } } }])]); return res.json({ success: true, data: { totalReservations, confirmedReservations, pendingReservations, completedReservations, cancelledReservations, totalRevenue: revenue[0]?.total || 0 } }); } catch (error) { return next(error); } }
export async function filterByStatus(req, res, next) { try { const data = await populate(Reservation.find({ status: req.query.status })); return res.json({ success: true, count: data.length, data }); } catch (error) { return next(error); } }
export async function filterByDateRange(req, res, next) { try { const data = await populate(Reservation.find({ checkInDate: { $gte: dateOnly(req.query.startDate), $lte: dateOnly(req.query.endDate) } })); return res.json({ success: true, count: data.length, data, dateRange: req.query }); } catch (error) { return next(error); } }
export async function searchReservationsHandler(req, res, next) { try { const query = req.query.query ? new RegExp(req.query.query, 'i') : null; const data = await populate(Reservation.find(query ? { $or: [{ reservationNumber: query }] } : {})); return res.json({ success: true, count: data.length, data }); } catch (error) { return next(error); } }
export async function getFilteredReservations(req, res, next) { try { const page = Number(req.query.page) || 1; const limit = Number(req.query.limit) || 10; const filter = req.query.status ? { status: req.query.status } : {}; const [data, total] = await Promise.all([populate(Reservation.find(filter).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit)), Reservation.countDocuments(filter)]); return res.json({ success: true, data, count: data.length, pagination: { page, limit, total, pages: Math.ceil(total / limit) } }); } catch (error) { return next(error); } }
export async function getReservationStatsByStatus(req, res, next) { try { const data = await Reservation.aggregate([{ $group: { _id: '$status', count: { $sum: 1 } } }]); return res.json({ success: true, data }); } catch (error) { return next(error); } }
export async function checkRoomAvailability(req, res, next) { try { const { checkInDate, checkOutDate } = req.query; if (!checkInDate || !checkOutDate) return res.status(400).json({ success: false, message: 'checkInDate and checkOutDate are required' }); const available = !(await Reservation.exists(conflictQuery(req.params.roomId, checkInDate, checkOutDate))); return res.json({ success: true, available }); } catch (error) { return next(error); } }