import mongoose from 'mongoose';
import Room from '../models/Room.js';
const byId = (id) => mongoose.isValidObjectId(id) ? { _id: id } : { roomNumber: id };
const roomPayload = (body) => ({ ...body, type: body.type || body.roomType, price: body.price ?? body.pricePerNight, floor: body.floor ?? (parseInt(String(body.roomNumber || '1')[0], 10) || 1) });
export async function getAllRooms(req, res, next) { try { const { search, type, status, housekeepingStatus, floor } = req.query; const query = {}; if (search) query.$or = [{ roomNumber: new RegExp(search, 'i') }, { type: new RegExp(search, 'i') }, { currentGuest: new RegExp(search, 'i') }]; if (type && type !== 'All') query.type = type; if (status && status !== 'All') query.status = status; if (housekeepingStatus && housekeepingStatus !== 'All') query.housekeepingStatus = housekeepingStatus; if (floor && floor !== 'All' && floor !== 'All Floors') query.floor = Number.parseInt(floor, 10); const data = await Room.find(query).sort({ roomNumber: 1 }); return res.json({ success: true, count: data.length, data }); } catch (error) { return next(error); } }
export async function getRoomById(req, res, next) { try { const data = await Room.findOne(byId(req.params.id)); if (!data) return res.status(404).json({ success: false, message: 'Room not found' }); return res.json({ success: true, data }); } catch (error) { return next(error); } }
export async function getAvailableRooms(req, res, next) { try { const { checkIn, checkOut, type } = req.query; const query = { status: { $nin: ['Maintenance', 'Occupied'] } }; if (type) query.type = type; if (checkIn && checkOut) { const Reservation = (await import('../models/Reservation.js')).default; const booked = await Reservation.find({ room: { $exists: true }, status: { $nin: ['Cancelled', 'Checked Out'] }, checkInDate: { $lt: new Date(checkOut) }, checkOutDate: { $gt: new Date(checkIn) } }).distinct('room'); query._id = { $nin: booked }; } const data = await Room.find(query).sort({ roomNumber: 1 }); return res.json({ success: true, count: data.length, data }); } catch (error) { return next(error); } }
export async function createRoom(req, res, next) { try { const payload = roomPayload(req.body); if (!payload.roomNumber || !payload.type || payload.price == null) return res.status(400).json({ success: false, message: 'Room number, type, and price are required' }); const data = await Room.create(payload); return res.status(201).json({ success: true, message: 'Room created successfully', data }); } catch (error) { return next(error); } }
export async function updateRoomData(req, res, next) { try { const data = await Room.findOneAndUpdate(byId(req.params.id), roomPayload(req.body), { new: true, runValidators: true }); if (!data) return res.status(404).json({ success: false, message: 'Room not found' }); return res.json({ success: true, message: 'Room updated successfully', data }); } catch (error) { return next(error); } }
export async function updateRoomStatus(req, res, next) { return updateRoomData(req, res, next); }
export async function deleteRoomData(req, res, next) { try { const data = await Room.findOneAndDelete(byId(req.params.id)); if (!data) return res.status(404).json({ success: false, message: 'Room not found' }); return res.json({ success: true, message: 'Room deleted successfully', data }); } catch (error) { return next(error); } }
export async function getRoomStats(req, res, next) { try { const [totalRooms, grouped] = await Promise.all([Room.countDocuments(), Room.aggregate([{ $group: { _id: '$status', count: { $sum: 1 } } }])]); const counts = Object.fromEntries(grouped.map((item) => [item._id, item.count])); return res.json({ success: true, data: { totalRooms, availableRooms: counts.Available || 0, occupiedRooms: counts.Occupied || 0, reservedRooms: counts.Reserved || 0, cleaningRooms: counts.Cleaning || 0, maintenanceRooms: counts.Maintenance || 0, occupancyRate: `${totalRooms ? ((counts.Occupied || 0) / totalRooms * 100).toFixed(2) : '0.00'}%` } }); } catch (error) { return next(error); } }