import Reservation from '../models/Reservation.js';
import Room from '../models/Room.js';
import Stay from '../models/Stay.js';
import Invoice from '../models/Invoice.js';
import Payment from '../models/Payment.js';

const details = (reservation) => ({ id: reservation.reservationNumber || reservation.id, guestId: reservation.guest?._id, roomId: reservation.room?._id, guestName: reservation.guest?.fullName || `${reservation.guest?.firstName || ''} ${reservation.guest?.lastName || ''}`.trim(), guestContact: reservation.guest?.phone, guestEmail: reservation.guest?.email, roomNumber: reservation.room?.roomNumber, roomType: reservation.room?.type, roomRate: reservation.room?.price, floor: reservation.room?.floor, checkInDate: reservation.checkInDate, checkOutDate: reservation.checkOutDate, numberOfGuests: (reservation.adults || 0) + (reservation.children || 0), totalAmount: reservation.totalAmount, status: reservation.status, specialRequests: reservation.specialRequests });

export async function searchCheckIn(req, res, next) { try { const query = new RegExp(req.query.query || '', 'i'); const reservation = await Reservation.findOne({ status: 'Confirmed', $or: [{ reservationNumber: query }] }).populate('guest').populate('room'); if (!reservation) return res.status(404).json({ success: false, message: 'Reservation not found' }); const data = details(reservation); return res.json({ success: true, id: data.id, guestName: data.guestName }); } catch (error) { return next(error); } }
export async function getCheckInReservation(req, res, next) { try { const reservation = await Reservation.findOne({ $or: [{ reservationNumber: req.params.id }, { _id: req.params.id }], status: 'Confirmed' }).populate('guest').populate('room'); if (!reservation) return res.status(404).json({ success: false, message: 'Reservation not found' }); return res.json({ success: true, ...details(reservation) }); } catch (error) { return next(error); } }
export async function confirmCheckIn(req, res, next) { try { const reservation = await Reservation.findOne({ $or: [{ reservationNumber: req.body.reservationId }, { _id: req.body.reservationId }], status: 'Confirmed' }).populate('guest').populate('room'); if (!reservation) return res.status(404).json({ success: false, message: 'Confirmed reservation not found' }); const stay = await Stay.create({ reservation: reservation._id, guest: reservation.guest._id, room: reservation.room._id, expectedCheckOut: reservation.checkOutDate, checkedInBy: req.user?.id }); await Reservation.findByIdAndUpdate(reservation._id, { status: 'Checked In' }); await Room.findByIdAndUpdate(reservation.room._id, { status: 'Occupied', currentGuest: reservation.guest.fullName }); return res.json({ success: true, message: 'Check-in confirmed successfully', data: { id: stay.id, reservationId: reservation.reservationNumber, guestId: reservation.guest._id, roomId: reservation.room._id, checkedInAt: stay.actualCheckIn, status: 'Checked In' } }); } catch (error) { return next(error); } }
export async function searchCheckOut(req, res, next) { try { const query = new RegExp(req.query.query || '', 'i'); const stay = await Stay.findOne({ status: 'Active' }).populate('guest').populate('room').populate('reservation'); if (!stay || !(query.test(stay.guest.fullName) || query.test(stay.room.roomNumber))) return res.status(404).json({ success: false, message: 'Active guest not found' }); return res.json({ success: true, guestId: stay.guest._id, reservationId: stay.reservation.reservationNumber, guestName: stay.guest.fullName, roomNumber: stay.room.roomNumber }); } catch (error) { return next(error); } }
export async function getCheckOutGuest(req, res, next) { try { const stay = await Stay.findOne({ guest: req.params.guestId, status: 'Active' }).populate('guest').populate('room').populate('reservation'); if (!stay) return res.status(404).json({ success: false, message: 'Active stay not found' }); const nights = Math.max(1, Math.ceil((Date.now() - stay.actualCheckIn) / 86400000)); return res.json({ success: true, guestId: stay.guest._id, reservationId: stay.reservation.reservationNumber, guestName: stay.guest.fullName, roomNumber: stay.room.roomNumber, checkInDate: stay.actualCheckIn, numberOfNights: nights, roomCharges: stay.room.price * nights, restaurantCharges: 0, additionalCharges: 0, subtotal: stay.room.price * nights, discount: 0, totalCharges: stay.room.price * nights }); } catch (error) { return next(error); } }
export async function processCheckOut(req, res, next) { try { const stay = await Stay.findOne({ guest: req.body.guestId, status: 'Active' }).populate('reservation').populate('room'); if (!stay) return res.status(404).json({ success: false, message: 'Active stay not found' }); const totalAmount = Number(req.body.totalAmount); if (!Number.isFinite(totalAmount) || totalAmount <= 0) return res.status(400).json({ success: false, message: 'A valid total amount is required' }); const invoice = await Invoice.create({ invoiceNumber: `INV-${Date.now()}`, guest: stay.guest, reservation: stay.reservation._id, stay: stay._id, roomCharges: totalAmount, totalAmount, paymentStatus: req.body.paymentMethod ? 'Paid' : 'Unpaid', amountPaid: req.body.paymentMethod ? totalAmount : 0 }); if (req.body.paymentMethod) await Payment.create({ paymentNumber: `PAY-${Date.now()}`, invoice: invoice._id, guest: stay.guest, amount: totalAmount, paymentMethod: req.body.paymentMethod, processedBy: req.user?.id }); await Stay.findByIdAndUpdate(stay._id, { status: 'Completed', actualCheckOut: new Date(), checkedOutBy: req.user?.id }); await Reservation.findByIdAndUpdate(stay.reservation._id, { status: 'Checked Out' }); await Room.findByIdAndUpdate(stay.room._id, { status: 'Cleaning', currentGuest: null }); return res.json({ success: true, message: 'Check-out completed successfully', data: { guestId: req.body.guestId, reservationId: req.body.reservationId, paymentMethod: req.body.paymentMethod, totalAmount, status: 'Checked Out' } }); } catch (error) { return next(error); } }